#!/usr/bin/env bash
#is a challenge
check_factor()
{
	if [ $# -ne 3 ];
        then
                args=("$@")
                count=0
                num2=1
                for a in ${args[*]};
                do
                        if [ $count -gt 1 ];
                        then
                                num2=$(echo $a*$num2 | bc)
                        fi
                        count=$((count + 1))
                done
        else
                num2=$3
        fi


}

if [ $# -ne 1 ]
then
        echo 'Usage: rsa <file>'
        exit 1
else

        while read i
        do

                result=$(factor "$i")
                check_factor $result

        done < "$1"
fi
